#! /bin/sh -x
# mme env yast2-network sp1

PKG=$1
SHORT_PRJ=$2
shift 2

case ${SHORT_PRJ-sp1} in
    factory)
        PRJ_BASE=""
        ;;
    121)
        PRJ_BASE=-121
        ;;
    114)
        PRJ_BASE=-114
        ;;
    113)
        PRJ_BASE=-113
        ;;
    sp2)
        PRJ_BASE=-sle11sp2
        ;;
    sp1)
        PRJ_BASE=-sle11sp1
        ;;
    sle10sp4)
        PRJ_BASE=-sle10sp4
        ;;
    sle10sp3)
        PRJ_BASE=-sle10sp3
        ;;
    *)
        echo missing case \'$SHORT_PRJ\' in $0
        return 1
        ;;
esac


export OSC_BUILD_ROOT=/var/tmp/build-root$PRJ_BASE
