#! /bin/sh -x
# mme env yast2-network sp1

PKG=$1
SHORT_PRJ=$2
shift 2

case ${SHORT_PRJ-sp1} in
    factory)
        PRJ_BASE=""
        ;;
    131|12[123]|11[34])
        PRJ_BASE=-$SHORT_PRJ
        ;;
    sp[123])
        PRJ_BASE=-sle11$SHORT_PRJ
        ;;
    sle10sp[234])
        PRJ_BASE=-$SHORT_PRJ
        ;;
    *)
        echo missing case \'$SHORT_PRJ\' in $0
        return 1
        ;;
esac


export OSC_BUILD_ROOT=/var/tmp/build-root$PRJ_BASE
