#! /bin/sh -x
# mkdir someplace; cd $_
# mme getvcs yast2-network sp1
## will check out to that dir

set -o errexit

GIT=""
USAGE=false
while getopts hg: FLAG; do
    case $FLAG in
	h) USAGE=true;;
	g) GIT="$OPTARG";;
	*) USAGE=true; RC=1;;
    esac
done
shift $((OPTIND-1))

if $USAGE; then
    echo "Usage: $0 [options] PKG SHORT_PRJ"
    echo " -h  Help"
    echo " -g <git URL> clone from here instead"
    exit $RC
fi

PKG=$1
SHORT_PRJ=$2
shift 2

if [ -n "$GIT" ]; then
    git clone "$GIT" .
    exit
fi

# assuming yast2, svn

case ${SHORT_PRJ-sp1} in
    factory)
        SVN_BRANCH=trunk
        ;;
    112)
        SVN_BRANCH=branches/SuSE-Linux-12_1-Branch
        ;;
    114)
        SVN_BRANCH=branches/SuSE-Linux-11_4-Branch
        ;;
    113)
        SVN_BRANCH=branches/SuSE-Linux-11_3-Branch
        ;;
    sp2)
        SVN_BRANCH=branches/SuSE-Code-11-SP2-Branch
        ;;
    sp1)
        SVN_BRANCH=branches/SuSE-Code-11-SP1-Branch
        ;;
    sle10sp4)
        SVN_BRANCH=branches/SuSE-SLE-10-SP4-Branch
        ;;
    sle10sp3)
        SVN_BRANCH=branches/SuSE-SLE-10-SP3-Branch
        ;;
    sle10sp2)
        SVN_BRANCH=branches/SuSE-SLE-10-SP2-Branch
        ;;
    *)
        echo missing case \'$SHORT_PRJ\' in $0
        exit 1
        ;;
esac


SVN_PKG=${PKG#yast2-}
svn co -q http://svn.opensuse.org/svn/yast/${SVN_BRANCH}/${SVN_PKG} .
