#! /bin/bash -x
# usage:
# OSC_BUILD_ROOT=/path [USER=joe] mme-chroot command [args]

set -o errexit
# logname is set by login(1)
: ${USER=$LOGNAME}
: ${ROOT=$OSC_BUILD_ROOT}

if [ -z "$ROOT" ]; then
    select ROOT in /var/tmp/build-root*/; do
        break
    done
fi


PASSWD=$ROOT/etc/passwd
if ! grep -q "^${USER}:" "$PASSWD"; then
    sudo sh -c "getent passwd ${USER} >> ${PASSWD}"
fi

# TODO set prompt, WM label
sudo chroot --userspec=$USER:users $ROOT \
    env HOME=/tmp \
        "${@-$SHELL}"
