#! /bin/sh -x
# mme getpac yast2-network sp1

# fd3 will be our output, stdout goes stderr
exec 3>&1 >&2

set -o errexit

USAGE=false
BRANCH=true
while getopts hg:B FLAG; do
    case $FLAG in
	h) USAGE=true;;
        B) BRANCH=false;;
	*) USAGE=true; RC=1;;
    esac
done
shift $((OPTIND-1))

if $USAGE; then
    echo "Usage: $0 [options] PKG SHORT_PRJ"
    echo " -h  Help"
    echo " -B  Don't branch the OBS project"
    exit $RC
fi

PKG=$1
SHORT_PRJ=$2
shift 2

API=https://api.suse.de

case ${SHORT_PRJ-sp1} in
    factory)
        API=https://api.opensuse.org
        PRJ=openSUSE:Factory
        ;;
    121)
        API=https://api.opensuse.org
        PRJ=openSUSE:12.1:Update
        ;;
    114)
        API=https://api.opensuse.org
        PRJ=openSUSE:11.4:Update:Test
        ;;
    113)
        API=https://api.opensuse.org
        PRJ=openSUSE:11.3:Update:Test
        ;;
    sp2)
        PRJ=SUSE:SLE-11-SP2:Update:Test
        ;;
    sp1)
        PRJ=SUSE:SLE-11-SP1:Update:Test
        ;;
    sle10sp4)
        PRJ=SUSE:SLE-10-SP4:Update:Test
        ;;
    sle10sp3)
        PRJ=SUSE:SLE-10-SP3:Update:Test
        ;;
    *)
        echo missing case \'$SHORT_PRJ\' in $0
        exit 1
        ;;
esac
: ${OSC_USER=$LOGNAME}
cd ~
DEVEL_PRJ=`osc -A $API develproject $PRJ $PKG`
case $DEVEL_PRJ in
    *has?no?devel?project)
        DEVEL_PRJ=$PRJ
        ;;
esac

if $BRANCH; then
    OSC_WORK=~/"home:$OSC_USER:branches:$DEVEL_PRJ"/$PKG
    osc -A $API bco $DEVEL_PRJ $PKG || test -d $OSC_WORK
else
    OSC_WORK=~/$DEVEL_PRJ/$PKG
    osc -A $API co $DEVEL_PRJ $PKG || test -d $OSC_WORK
fi
cd $OSC_WORK
osc up --expand-link

echo >&3 $OSC_WORK
