#! /bin/bash -x
# usage:
# OSC_BUILD_ROOT=/path [USER=joe] mme-chroot command [args]

set -o errexit
# logname is set by login(1)
: ${USER=$LOGNAME}
: ${ROOT=$OSC_BUILD_ROOT}

if [ -z "$ROOT" ]; then
    select ROOT in /var/tmp/build-root*/; do
        break
    done
fi


PASSWD=$ROOT/etc/passwd
if ! grep -q "^${USER}:" "$PASSWD"; then
    sudo sh -c "getent passwd ${USER} >> ${PASSWD}"
fi

# m DIR CMD...
# bind-mount /DIR to $ROOT/DIR; do CMD; then unmount
m() {
    local M=$1
    shift
    sudo mount --bind /$M $ROOT/$M
    "$@"
    sudo umount $ROOT/$M
}

# TODO set prompt, WM label
m proc m dev m sys m run \
  sudo chroot --userspec=$USER:users $ROOT \
    env HOME=/tmp \
      "${@-$SHELL}"
