#! /bin/sh -x
# mme-makepac --clone /a-chroot/tmp/mme-makepac
# mme-makepac yast2-network sp1

# fd3 will be our output, stdout goes stderr
exec 3>&1 >&2

set -o errexit

if [ "$1" = --clone ]; then
    DEST=$2
    cp $0 $DEST
    chmod +x $DEST
    exit
fi

PKG=$1
SHORT_PRJ=$2
shift 2

if test $PKG = yast2-devtools; then
    OPTS=Y2DEVTOOLS_PREFIX=/usr
fi

if test -f CMakeLists.txt -o -f PROJECTINFO.cmake; then
    ./bootstrap.sh || :
    mkdir build
    cd build
    # from spec
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DLIB=`rpm --eval '%{_lib}'` \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_SKIP_RPATH=1 \
      ..
    make srcpackage
elif test -f Makefile.cvs; then
    # assuming yast2, svn
    make -f Makefile.cvs
    make package-local CHECK_SYNTAX=false $OPTS
else
    echo >&2 "Did not recognize the build system"
    exit 1
fi

cd package
pwd >&3
