#! /bin/sh -x
# mme getpac yast2-network sp1

# fd3 will be our output, stdout goes stderr
exec 3>&1 >&2

set -o errexit
PKG=$1
SHORT_PRJ=$2
shift 2
case ${SHORT_PRJ-sp1} in
    114)
        API=https://api.opensuse.org
        PRJ=openSUSE:11.4:Update:Test
        ;;
    sp1)
        API=https://api.suse.de
        PRJ=SUSE:SLE-11-SP1:Update:Test
        ;;
    sp2)
        API=https://api.suse.de
        PRJ=SUSE:SLE-11-SP2:GA
        ;;
    *)
        echo missing case \'$SHORT_PRJ\'
        exit 1
        ;;
esac
: ${OSC_USER=$LOGNAME}
cd ~
OSC_WORK=~/"home:$OSC_USER:branches:$PRJ"/$PKG
osc -A $API bco $PRJ $PKG || test -d $OSC_WORK

echo >&3 $OSC_WORK
